language: ruby

rvm:
  - 2.3.1

bundler_args: --without production

cache: bundler

before_script:
  - bundle exec rake db:environment:set RAILS_ENV=test
  - bundle exec rake db:migrate:reset RAILS_ENV=test

script:
  - bundle exec rspec
